/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface": "#faf9f6",
        "surface-dim": "#dbdad7",
        "surface-bright": "#faf9f6",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f4f3f0",
        "surface-container": "#efeeeb",
        "surface-container-high": "#e9e8e5",
        "surface-container-highest": "#e3e2df",
        "on-surface": "#1b1c1a",
        "on-surface-variant": "#444748",
        "inverse-surface": "#2f312f",
        "inverse-on-surface": "#f2f1ee",
        "outline": "#747878",
        "outline-variant": "#c4c7c7",
        "surface-tint": "#5f5e5e",
        "primary": "#040505",
        "on-primary": "#ffffff",
        "primary-container": "#1e1e1e",
        "on-primary-container": "#878585",
        "inverse-primary": "#c8c6c5",
        "secondary": "#954a00",
        "on-secondary": "#ffffff",
        "secondary-container": "#fd933f",
        "on-secondary-container": "#693300",
        "tertiary": "#00060d",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#002133",
        "on-tertiary-container": "#008fcb",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "background": "#faf9f6",
        "on-background": "#1b1c1a",
        "surface-variant": "#e3e2df",
      },
      fontFamily: {
        brandmark: ["'EB Garamond'", "serif"],
        "display-hero": ["'Space Grotesk'", "sans-serif"],
        "display-hero-mobile": ["'Space Grotesk'", "sans-serif"],
        "headline-lg": ["'Space Grotesk'", "sans-serif"],
        "headline-lg-mobile": ["'Space Grotesk'", "sans-serif"],
        "headline-sm": ["'Space Grotesk'", "sans-serif"],
        "body-lg": ["'DM Sans'", "sans-serif"],
        "body-sm": ["'DM Sans'", "sans-serif"],
        "mono-spec": ["'Space Mono'", "monospace"],
        "mono-label": ["'Space Mono'", "monospace"],
        "button-text": ["'Space Mono'", "monospace"],
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "2rem",
        "space-xl": "3.5rem",
        "space-2xl": "5rem",
      },
      borderRadius: {
        DEFAULT: "0px",
        none: "0px",
      }
    },
  },
  plugins: [],
}
